CAPABILITY_LIST = (
    "System capabilities — WardLog can:\n"
    "- Save and fetch logged activities (clinic blocks, surgery blocks, "
    "on-call shifts, on-site on-call shifts).\n"
    "- Save and fetch patients and consultations — a patient's diagnoses, "
    "drugs, and surgery type, linked to the activity they were seen during.\n"
    "- Extract, save, and fetch reports (patient, report type, date, "
    "findings).\n"
    "- Get data about any of the above from the doctor's own records in the "
    "database.\n"
    "These are the only things the system can do. Do not offer, promise, or "
    "imply any capability outside this list — for example medical advice, "
    "diagnoses, treatment recommendations, reminders, notifications, "
    "scheduling, summaries or exports it can't produce, or integrations with "
    "other systems."
)
