server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - "*"
                allowedMethods:
                  - "*"
                allowedHeaders:
                  - "*"
                allowCredentials: true
          routes:
            - id: user-service-auth
              uri: lb://user-microservice
              predicates:
                - Path=/api/v1/auth/**
            - id: user-service
              uri: lb://user-microservice
              predicates:
                - Path=/api/v1/users/**
            - id: timesheet-service
              uri: lb://timesheet-service
              predicates:
                - Path=/api/v1/activities/**,/api/v1/timesheet/**
            - id: ai-service
              uri: lb://ai-service
              predicates:
                - Path=/api/v1/conversations/**

jwt:
  secret: Ij86dwGTkT1K9jMS1DIzUDkttmHMPP01VgG8tWRYgxUFIQCFRe+NdXpP2HHco2UYPdRqh80ZzIDF2wdgiJ6fow==

security:
  public-paths:
    - /api/v1/auth/login
    - /api/v1/auth/register
    - /api/v1/auth/refresh

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,gateway