from typing import Literal, Optional

from pydantic import BaseModel


class DoctorContext(BaseModel):
    id: str

    name: str
    age: int
    sex: Optional[str] = None
    # the tone selected affects the output generated by the AI
    tone: Literal["warm", "funny", "professional"]
    # this makes the response short and on point representing the user is in a hurry
    rush: bool
    assistant_name: str = "wardlog"
    # when true, the assistant's reply is also produced as speech
    voice_output: bool = False
